export const dummyData = [
  {
    imgSrc:
      "https://images.unsplash.com/photo-1532614338840-ab30cf10ed36?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1532614338840-ab30cf10ed36?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "Places",
    alt: "Yosemite National Park",
    title: "Yosemite National Park",
    location: "California",
    views: "6.3k views",
    time: "1 hour ago",
    tags: [
      "nature",
      "park",
      "hiking",
      "mountains",
      "trees",
      "scenery",
      "wildlife",
      "outdoors",
      "national park",
      "landscape",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "flipkart",
    alt: "Grand Canyon",
    title: "Grand Canyon",
    location: "Arizona",
    views: "4.2k views",
    time: "2 hours ago",
    tags: [
      "nature",
      "canyon",
      "geology",
      "desert",
      "landscape",
      "hiking",
      "scenery",
      "national park",
      "views",
      "adventure",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "amazon",
    alt: "Mount Fuji",
    title: "Mount Fuji",
    location: "Japan",
    views: "3.8k views",
    time: "3 hours ago",
    tags: [
      "mountain",
      "volcano",
      "Japan",
      "scenery",
      "nature",
      "snow",
      "views",
      "travel",
      "hiking",
      "landmark",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "degen",
    alt: "Machu Picchu",
    title: "Machu Picchu",
    location: "Peru",
    views: "7.1k views",
    time: "4 hours ago",
    tags: [
      "ancient",
      "ruins",
      "Peru",
      "Inca",
      "mountains",
      "history",
      "landmark",
      "scenery",
      "hiking",
      "adventure",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "akki",
    alt: "Eiffel Tower",
    title: "Eiffel Tower",
    location: "France",
    views: "9.5k views",
    time: "5 hours ago",
    tags: [
      "landmark",
      "Paris",
      "France",
      "tower",
      "cityscape",
      "architecture",
      "travel",
      "views",
      "iconic",
      "tourism",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1532614338840-ab30cf10ed36?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1506784983877-45594efa4cbe?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "deb",
    alt: "Great Wall of China",
    title: "Great Wall of China",
    location: "China",
    views: "8.3k views",
    time: "6 hours ago",
    tags: [
      "landmark",
      "China",
      "wall",
      "ancient",
      "history",
      "architecture",
      "views",
      "travel",
      "tourism",
      "hiking",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1506784365847-bbad939e9335?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "kavish",
    alt: "Colosseum",
    title: "Colosseum",
    location: "Italy",
    views: "5.7k views",
    time: "7 hours ago",
    tags: [
      "landmark",
      "Rome",
      "Italy",
      "ancient",
      "architecture",
      "history",
      "arena",
      "travel",
      "tourism",
      "views",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1483683804023-6ccdb62f86ef?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "kavish",
    alt: "Statue of Liberty",
    title: "Statue of Liberty",
    location: "USA",
    views: "10.1k views",
    time: "8 hours ago",
    tags: [
      "landmark",
      "USA",
      "New York",
      "statue",
      "freedom",
      "iconic",
      "travel",
      "views",
      "tourism",
      "architecture",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "degen",
    alt: "Sydney Opera House",
    title: "Sydney Opera House",
    location: "Australia",
    views: "7.9k views",
    time: "9 hours ago",
    tags: [
      "landmark",
      "Australia",
      "Sydney",
      "architecture",
      "opera",
      "views",
      "tourism",
      "iconic",
      "harbor",
      "travel",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1481391609890-331b6ff365ba?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "degen",
    alt: "Christ the Redeemer",
    title: "Christ the Redeemer",
    location: "Brazil",
    views: "6.8k views",
    time: "10 hours ago",
    tags: [
      "landmark",
      "Brazil",
      "Rio de Janeiro",
      "statue",
      "views",
      "iconic",
      "tourism",
      "travel",
      "architecture",
      "mountain",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1546534857-505b6d1af7d9?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "deb",
    alt: "Pyramids of Giza",
    title: "Pyramids of Giza",
    location: "Egypt",
    views: "9.3k views",
    time: "11 hours ago",
    tags: [
      "landmark",
      "Egypt",
      "pyramids",
      "ancient",
      "history",
      "architecture",
      "views",
      "tourism",
      "travel",
      "desert",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1531306152480-58b29fae78e9?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "google",
    alt: "Santorini",
    title: "Santorini",
    location: "Greece",
    views: "8.7k views",
    time: "12 hours ago",
    tags: [
      "island",
      "Greece",
      "Santorini",
      "views",
      "sunset",
      "architecture",
      "tourism",
      "travel",
      "Mediterranean",
      "scenery",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1561484936-f1e8141635b4?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1472214103451-9374bd1c798e?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "google",
    alt: "Petra",
    title: "Petra",
    location: "Jordan",
    views: "5.9k views",
    time: "13 hours ago",
    tags: [
      "ancient",
      "Jordan",
      "Petra",
      "history",
      "architecture",
      "ruins",
      "landmark",
      "travel",
      "tourism",
      "desert",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "google",
    alt: "Stonehenge",
    title: "Stonehenge",
    location: "England",
    views: "4.5k views",
    time: "14 hours ago",
    tags: [
      "landmark",
      "England",
      "Stonehenge",
      "ancient",
      "history",
      "mystery",
      "architecture",
      "tourism",
      "views",
      "travel",
    ],
  },
  {
    imgSrc:
      "https://images.unsplash.com/photo-1542261750-ecf1d03683c5?auto=format&fit=crop&w=318",
    imgSrcSet:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=318&dpr=2 2x",
    appName: "amazon",
    alt: "Taj Mahal",
    title: "Taj Mahal",
    location: "India",
    views: "11.2k views",
    time: "15 hours ago",
    tags: [
      "landmark",
      "India",
      "Taj Mahal",
      "architecture",
      "history",
      "marble",
      "views",
      "tourism",
      "travel",
      "iconic",
    ],
  },
];
